"""Frozen method-blind root decisions for the E2 adjudication queues.

Each character maps positionally to the immutable card order in
``root_audit/identity_cards.jsonl`` or ``root_audit/relation_cards.jsonl``.
The mappings and exact-coverage checks live in :mod:`e2_root_audit`.

These codes were assigned from the clinical record, reference diagnosis and
the two heterogeneous reviewer rationales before joining case keys, method
arms, strict/task outcomes, mapper outcomes, sampling strata, or queue reasons.
"""

IDENTITY_DECISION_CODES = (
    "FQQFQQQFQFFFFQSQQSQSQFQFFFQQQFFQQFQFFFSFQFFQQFQQQFFFQFFFQFFQFSQFFQFQQQQS"
    "FQQQQFFQFQFQFFQQQQQQQQQQQFQQFQQQQFFQQQFQQQFQQQQQQQQQQQQFSSQFQFQFFSSSSQQQ"
    "FQQQQSFSQSSQSQQQSSSSQQFQFFQQSSQQSSQQQQQQQQFSSSFQSFFQQQFQSFQQQFSQFFFQQSSQ"
    "SFQQSSFQSQFQQSFSFSQQFQFFQSF"
)

RELATION_DECISION_CODES = (
    "PPPPPXPMPPPPPPXNNCCCCNPNMNXCPNNNXXPNMMPMMNXPMPXXPNNPPCNPNPCCMPPPNMPNPNCP"
    "PXXXCCPPPPNPMPPPPMPPMMMPPPPMPMMPXPPMMMXXXMMMXPCPCXMMMMMMNPPMPPPPPXPCPPNC"
    "PPNPPNXPXCPXNNPNCMMMMNPXXMNPMMPCCCPPNXNNNNNPXXCMNMMMPPNPNXPXPPMMXMPPCCPP"
    "PPNNPPPPCPPPCPXCPPNCCCCCNCPNMMMMPMMMPXNNNNNNNCMMMMMMMNMMMCCCXXMPCCCPNCMM"
    "MCMCCMMMMMMMMCCPMMCNCNMCCCCXXXMMPNMCPNCPCXNXCCXNMMMMMMCMMCCMMMCPCCNNNNCN"
    "NCCPXNMNMCMMCNPCCPCCPNMNPPCCCNCCMNMNNNNMXNXMNMXNPPNPPPPCPNPNNNNMNCPPCPCC"
    "PXPPPCNNNCNNNXXCNNNNNNPNNNNNNMCCMMCNPNCPPPPPPPMMXXXXXXPCCCMPPNMCCCCCCCMP"
    "NMNNCNNCCPXPPCNCCNPMMMXCPXPMPMMMN"
)
